// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIaENeV8SVA7MpggcLO3gNwJQXf4r3HJc',
    appId: '1:218376153281:web:3c2c015678ebb358600c40',
    messagingSenderId: '218376153281',
    projectId: 'integration-ad400',
    authDomain: 'integration-ad400.firebaseapp.com',
    storageBucket: 'integration-ad400.appspot.com',
    measurementId: 'G-NWXJKDC2HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sy2dFWBFXIDC-DwZ8T5y0Gh2_OvX--o',
    appId: '1:218376153281:android:939746aad4fc98ae600c40',
    messagingSenderId: '218376153281',
    projectId: 'integration-ad400',
    storageBucket: 'integration-ad400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OqLKbWbyi3G1hMFwSGbLXf86WcPyrWE',
    appId: '1:218376153281:ios:c82ce997736d50a7600c40',
    messagingSenderId: '218376153281',
    projectId: 'integration-ad400',
    storageBucket: 'integration-ad400.appspot.com',
    iosBundleId: 'com.example.firebaseIntegApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OqLKbWbyi3G1hMFwSGbLXf86WcPyrWE',
    appId: '1:218376153281:ios:c82ce997736d50a7600c40',
    messagingSenderId: '218376153281',
    projectId: 'integration-ad400',
    storageBucket: 'integration-ad400.appspot.com',
    iosBundleId: 'com.example.firebaseIntegApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIaENeV8SVA7MpggcLO3gNwJQXf4r3HJc',
    appId: '1:218376153281:web:093ed7a79341d2b5600c40',
    messagingSenderId: '218376153281',
    projectId: 'integration-ad400',
    authDomain: 'integration-ad400.firebaseapp.com',
    storageBucket: 'integration-ad400.appspot.com',
    measurementId: 'G-1D5WV9FRJS',
  );
}
